version: '3.4'
services:
  mysql_legacy:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: lucid
      MYSQL_USER: virk
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    expose:
      - '3306'
  mysql_replica_1:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: lucid
      MYSQL_USER: virk
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3304:3306'
    expose:
      - '3306'
  mysql_replica_2:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: lucid
      MYSQL_USER: virk
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3303:3306'
    expose:
      - '3306'
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync
    environment:
      MYSQL_DATABASE: lucid
      MYSQL_USER: virk
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3305:3306'
    expose:
      - '3306'
  pg:
    image: postgres:11
    environment:
      POSTGRES_DB: lucid
      POSTGRES_USER: virk
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    expose:
      - '5432'
  microsoftsql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 21433:1433
    expose:
      - '1433'
    environment:
      SA_PASSWORD: 'arandom&233password'
      ACCEPT_EULA: 'Y'
