name: test
on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npx tsc

  test-postgres:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [14, 16, 18]
        postgres-version: [11, 14]
    services:
      postgres:
        image: postgres:${{ matrix.postgres-version }}
        env:
          POSTGRES_DB: lucid
          POSTGRES_USER: virk
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Run Postgres Tests
        run: npm run test:pg

  test-mysql:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mysql: [{ version: '5.7', command: 'mysql_legacy' }, { version: '8.0', command: 'mysql' }]
        node-version: [14, 16, 18]
    services:
      mysql:
        image: mysql:${{ matrix.mysql.version }}
        env:
          MYSQL_DATABASE: lucid
          MYSQL_USER: virk
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
        ports:
          - '3306:3306'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Run Mysql Tests
        run: npm run test:${{ matrix.mysql.command }}

  test-sqlite:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lib: ['sqlite', 'better_sqlite']
        node-version: [14, 16, 18]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Run Sqlite Tests
        run: npm run test:${{ matrix.lib }}

  test-mssql:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [16, 18]
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: 'arandom&233password'
          ACCEPT_EULA: 'Y'
        ports:
          - '1433:1433'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Run Mssql Tests
        run: npm run test:mssql
